### PR TITLE
Backwards compatible way of importing reverse

### PR DESCRIPTION
**Pull request by svleeuwen**
Makes this library compatible with Django 1.10+

### CODE REVIEW

**Comment by bashu** [comment]
@svleeuwen I don't have access to the repo anymore, can not help here...

**Comment by Asday** [comment]
Who removed you, @bashu?  I don't see any reason to revoke the access given to you in #29.

**Comment by bashu** [comment]
@Asday I can not merge this PR

**Comment by Asday** [comment]
Appreciated, but do you have any notification or having your access revoked?

**Comment by bashu** [comment]
@Asday don't know

**Comment by Asday** [comment]
@sanderl-mediamonks That last commit has nothing to do with this PR.

**Comment by svleeuwen** [comment]
@Asday Right, this PR shouldn't have come from my master anyway. I think the best approach would be to remove this PR and create a new one.

**Comment by svleeuwen** [comment]
Close in favor of #36

**Pull request closed without merging**
