### PR TITLE
Merge django-ya-model-publisher ?!?

### PR DESCRIPTION
**Pull request by jedie**
Is there interest to mege **django-ya-model-publisher** ?

https://github.com/wearehoods/django-ya-model-publisher

### CODE REVIEW

**Comment by bashu** [comment]
@jedie holy smoke! is there any chance to split it onto several separate PR?

**Comment by bashu** [comment]
@jedie answering your question, yes there is chance to merge it back, but only after reviewing and not everything

**Comment by jedie** [comment]
Actually, I was just checking to see if there's any general interest.

> yes there is chance to merge it back, but only after reviewing and not everything

What do you mean with "not everything" ?

The publisher workflow is important to me. However, there is still room for improvement.

**Comment by bashu** [comment]
@jedie yes there is interest, however I need to review this *huge* PR first, can you tell more about changes you made?

**Comment by jedie** [comment]
Look into the README: https://github.com/wearehoods/django-ya-model-publisher#readme

The main part is the "publisher workflow", see: https://github.com/wearehoods/django-ya-model-publisher#base-info

You can try out the test project, see: https://github.com/wearehoods/django-ya-model-publisher#run-test-project

**Comment by Asday** [comment]
What @bashu is saying is that you've put WAY too much into this one PR.

Just a quick scroll through the commits, I can see several things that should be their own, _small_, PR:

* Bugfix test for djang 1.8
* Bugfix: redirect to "/?edit_off" see: wearehoods#9
* Bugfix: Missing "Request publishing" toobar link on new created pages

And I'm sure many more.

Each PR should contain one singular feature, bugfix, or enhancement.  This makes them very easy to review and merge quickly, whereas reviewing this would take literally months.

@bashu are you ok to close this one?

**Comment by bashu** [comment]
@Asday @jedie I am going to review / merge change and I'm closing this PR

**Comment by Asday** [comment]
Much appreciated.  I was getting sick of the emails.  :eyes:

**Pull request closed without merging**
