### PR TITLE
Update compatibility for Django 1.7-1.11

### PR DESCRIPTION
**Pull request by cdobbyn**
Added testing and support for

- Django 1.7 - 1.11
- Python 2.7 - 3.6

Dropped support for

- Django version older than 1.7
- Python 2.6

### CODE REVIEW

**Comment by cdobbyn** [comment]
Just found that Admin is broken, not covered by tests so it didn't come up in Travis. Working through that now.

**Comment by iraycd** [comment]
@cdobbyn When will you launch this new version?

**Comment by AlJohri** [comment]
@cdobbyn any luck?

**Comment by jedie** [comment]
see also #29

**Comment by jedie** [comment]
Take a look at my fork called **django-ya-model-publisher**:

github: https://github.com/wearehoods/django-ya-model-publisher/
PyPi: https://pypi.org/project/django-ya-model-publisher/

**Comment by bashu** [comment]
@cdobbyn thanks a lot!

**Pull request merged**
